; This file describes fixture build properties

[fixtures]
timestamp = 2025-04-08T13:59:44.601119
build = develop
ref = refs/tags/v4.2.0
commit = 36c5f133085765f0f7cca3c324269460ae738035
command_line_args = fill -n 10 --evm-bin=ethereum-spec-evm-resolver --solc-version=0.8.21 --skip-evm-dump --until=Prague --output=fixtures_develop.tar.gz --build-name develop

[packages]
pytest = 7.4.4
pluggy = 1.5.0

[plugins]
regex = 0.2.0
metadata = 3.1.1
xdist = 3.6.1
json-report = 1.5.0
custom-report = 1.0.1
html = 4.1.1

[tools]
eels resolutions = /home/usainbolt/runner2/_work/execution-spec-tests/execution-spec-tests/eels_resolutions.json
t8n = ethereum-spec-evm-resolver 0.0.5
solc = 0.8.21

[environment]
python = 3.10.16
platform = Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
ci = true

